# Generated by Django 5.0 on 2024-01-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='musician',
            new_name='musician_Model',
        ),
    ]
