# Generated by Django 5.0 on 2024-01-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_rating',
            field=models.CharField(choices=[('three', '3'), ('five', '5'), ('one', '1'), ('four', '4'), ('two', '2')], max_length=10),
        ),
    ]
