# Generated by Django 5.0 on 2024-01-19 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_albums_model_album_rating'),
        ('musicians', '0002_rename_musician_musician_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums_model',
            name='Artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicians.musician_model'),
        ),
    ]
